title = "<green>ApolloCraft</green> <gray>• Utilidades"
rows = 4
open-actions = ["sound:ITEM_BOOK_PAGE_TURN 0.7 1.2"]

items {
  kits {
    slot = 10
    material = CHEST
    name = "<yellow><bold>Kits</bold>"
    lore = ["<gray>Veja e resgate seus kits."]
    click { left = ["close", "command:kit"] }
  }

  cofres {
    slot = 11
    material = ENDER_CHEST
    name = "<dark_purple><bold>Cofres pessoais</bold>"
    lore = ["<gray>Abra seus espaços de armazenamento."]
    click { left = ["close", "command:vault"] }
  }

  bancada {
    slot = 12
    material = CRAFTING_TABLE
    name = "<gold><bold>Bancada de trabalho</bold>"
    lore = ["<gray>Crie itens de qualquer lugar."]
    click { left = ["close", "command:workbench"] }
  }

  bigorna {
    slot = 13
    material = ANVIL
    name = "<gray><bold>Bigorna</bold>"
    lore = ["<gray>Abra uma bigorna virtual."]
    click { left = ["close", "command:anvil"] }
  }

  enderchest {
    slot = 14
    material = ENDER_CHEST
    name = "<light_purple><bold>Ender Chest</bold>"
    lore = ["<gray>Acesse seu baú do Ender."]
    click { left = ["close", "command:enderchest"] }
  }

  receitas {
    slot = 15
    material = KNOWLEDGE_BOOK
    name = "<aqua><bold>Receitas</bold>"
    lore = ["<gray>Consulte receitas de itens."]
    click { left = ["close", "command:recipe"] }
  }

  lixeira {
    slot = 16
    material = LAVA_BUCKET
    name = "<red><bold>Lixeira</bold>"
    lore = ["<gray>Descarte itens em uma tela segura."]
    click { left = ["close", "command:disposal"] }
  }

  itens {
    slot = 20
    material = ITEM_FRAME
    name = "<blue><bold>Ferramentas de itens</bold>"
    lore = ["<gray>Abra a central de itens."]
    click { left = ["close", "command:itemworld"] }
  }

  poses {
    slot = 22
    material = ARMOR_STAND
    name = "<yellow><bold>Poses</bold>"
    lore = ["<gray>Escolha uma pose divertida."]
    click { left = ["close", "command:poses"] }
  }

  placar {
    slot = 24
    material = MAP
    name = "<green><bold>Placar</bold>"
    lore = ["<gray>Ajuste a barra lateral."]
    click { left = ["close", "command:scoreboard"] }
  }

  menu {
    slot = 31
    material = ARROW
    name = "<yellow>Voltar ao menu"
    click { left = ["open:apollo"] }
  }
}
