name: Build ApolloCraft Essentials

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Dar permissao ao Gradle
        run: chmod +x gradlew

      - name: Compilar ApolloCraft Essentials
        run: ./gradlew --no-daemon :bukkit-adapter:shadowJar

      - name: Enviar JAR
        uses: actions/upload-artifact@v4
        with:
          name: ApolloCraft-Essentials
          path: bukkit-adapter/build/libs/*.jar
          if-no-files-found: error
